<a href="https://colab.research.google.com/github/thakur785/sandbox_ai/blob/deeplearnig_pytorc/Pytorch/Deeplearningwithpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu128
True


Creating Tensor CPU example

In [ ]:
import torch
first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])
add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [ ]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating tensor GPU example

In [ ]:
import torch
print(torch.__version__)


2.9.0+cu128


In [ ]:
if torch.cuda.is_available(): device = "cuda"
else : device = "cpu"
print(device)

cuda


In [ ]:
tens_a = torch.tensor([[10,11,12,13],[14,15,16,17]], device = device)
tens_b = torch.tensor([[18,19,20,21],[22,23,24,25]], device = device)
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]], device='cuda:0')


Different ways to create tensors

In [ ]:
import torch
import numpy as np

tensor_from_list = torch.tensor([[1,2,3,4],[5,6,7,8]])
tensor_from_tuple = torch.tensor(((1,2,3,4),(5,6,7,8)))
print("tensor from list")
print(tensor_from_list)
print("tensor from tuple")
print(tensor_from_tuple)

tensor from list
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor from tuple
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
tensor_from_array = torch.tensor(np.array([11,12,13,14,15]))
print(tensor_from_array)

tensor([11, 12, 13, 14, 15])


Different functions for creating tensors


In [ ]:
tensor_emp = torch.empty(3,4)
print("empty tensor", tensor_emp)

empty tensor tensor([[ 1.1948e+13,  4.4970e-41,  1.8077e-43,  0.0000e+00],
        [-8.5339e-32,  4.4972e-41,  1.7544e-08,  0.0000e+00],
        [ 1.1949e+13,  4.4970e-41,  1.6413e-38,  0.0000e+00]])


In [ ]:
tensor_zeros = torch.zeros(3,4)
print("zeros tensor", tensor_zeros)

zeros tensor tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
tensor_ones = torch.ones(3,4)
print("ones tensor", tensor_ones)

ones tensor tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(3,4)
print("random tensor", tensor_rand_un)
tensor_rand_norm = torch.randn(3,4)
print("random normal tensor", tensor_rand_norm)

random tensor tensor([[0.6779, 0.9679, 0.3722, 0.2360],
        [0.8971, 0.5406, 0.8699, 0.7965],
        [0.6343, 0.7491, 0.3978, 0.4595]])
random normal tensor tensor([[-1.6030,  1.1690,  0.2953,  0.8439],
        [-0.9203,  0.7793,  1.1797, -1.0250],
        [ 1.5558, -0.7685,  0.0389, -0.8939]])


Manipulate tensors


In [ ]:
import torch

one_dim_tensor = torch.tensor([1,2,3,4,5,6])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

#slicing of tensor
one_dim_tensor[1:4]

tensor(3)
3


tensor([2, 3, 4])

In [ ]:
#Indexing two dim tensor
two_dim_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(two_dim_tensor)
two_dim_tensor[1,3]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


tensor(9)

In [ ]:
#slicing 2-Dim tensor example
print("first three elements of first row", two_dim_tensor[0,0:3])
print("elements of first row", two_dim_tensor[0,:])


first three elements of first row tensor([1, 2, 3])
elements of first row tensor([1, 2, 3, 4, 5])


In [ ]:
#extract 2-Dim tensor that meet some criteria
print(two_dim_tensor[two_dim_tensor<11])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
#combine 2-Dim tensor
combin_2d_tensors = torch.stack((two_dim_tensor,two_dim_tensor,two_dim_tensor,two_dim_tensor))
print(combin_2d_tensors)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])


In [ ]:
#splitting tensors
first_tensor, second_tensor, third_tensor, fourth_tensor = torch.unbind(two_dim_tensor)
print(first_tensor)
print(second_tensor)
print(third_tensor)
print(fourth_tensor)

tensor([1, 2, 3, 4, 5])
tensor([ 6,  7,  8,  9, 10])
tensor([11, 12, 13, 14, 15])
tensor([16, 17, 18, 19, 20])


Built-in mathematical functions
1) pointwise operations
2) Reduction functions
3) Comparison functions
4) Linear algebra operations
5) Spectral and other math computations - data transformation or analysis


In [1]:
#basic math functions
import torch
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([10,12,13,14,15])
print('adding tensors a and b:', a.add(b))

adding tensots a and b: tensor([11, 14, 16, 18, 20])


In [4]:
print('substracting tensor a from b:', b.sub(a))
print('multiplying tensor a and b:', a.mul(b))
print('divinding tensor a from b:', a.div(b))

substracting tensor a from b: tensor([ 9, 10, 10, 10, 10])
multiplying tensor a and b: tensor([10, 24, 39, 56, 75])
divinding tensor a from b: tensor([0.1000, 0.1667, 0.2308, 0.2857, 0.3333])


In [8]:
#reduction functions
c = torch.tensor([[20., 14. ,11. ,18.],[3., 19., 14., 6.]])
print('Mean of tensor c:', torch.mean(c))
print('Median of tensor c:', torch.median(c))
print('Mode of tensor c:',torch.mode(c))
print('Standard deviation of tensor:', torch.std(c))

Mean of tensor c: tensor(13.1250)
Median of tensor c: tensor(14.)
Mode of tensor c: torch.return_types.mode(
values=tensor([11.,  3.]),
indices=tensor([2, 0]))
Standard deviation of tensor: tensor(6.1514)


Linear algebra operations
PyTorch has a module called torch.linalg that contains a set of built-in linear
algebra functions that are based on BLAS and LAPACK standardized libraries.

In [10]:
#computing eigenvalues and eignvector
#create a 4X4 square matrix
A = torch.randn(4,4)
print('Matrix:', A)

eigenvalue, eigenvector = torch.linalg.eig(A)
print('Eigenvalue:', eigenvalue)
print('Eigenvector:', eigenvector)

Matrix: tensor([[-0.0933, -0.8658,  1.1337, -0.6436],
        [ 0.3915,  0.1429,  1.1446,  0.1543],
        [-1.7471,  0.3265,  0.6521, -1.1040],
        [-0.0066, -0.1977,  0.0990,  0.4813]])
Eigenvalue: tensor([-0.2055+1.5765j, -0.2055-1.5765j,  1.0605+0.0000j,  0.5336+0.0000j])
Eigenvector: tensor([[ 0.6179+0.0000j,  0.6179-0.0000j, -0.1050+0.0000j, -0.5489+0.0000j],
        [ 0.3144-0.3942j,  0.3144+0.3942j, -0.7725+0.0000j, -0.1904+0.0000j],
        [ 0.2249+0.5540j,  0.2249-0.5540j, -0.6051+0.0000j,  0.0131+0.0000j],
        [ 0.0810-0.0074j,  0.0810+0.0074j,  0.1615+0.0000j,  0.8138+0.0000j]])


In [12]:
#matix multiplication using matmul
first_2d_tensor = torch.tensor([[1,2,3],[-1,-2,-3]])
second_2d_tensor = torch.tensor([[1,2],[4,5],[7,8]])
result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
print(result_2d_tensor)

tensor([[ 30,  36],
        [-30, -36]])


In [13]:
# linalg.multi_dot to compute product of 5 2d tensors
first_2d_tensor = torch.randn(2,3)
second_2d_tensor = torch.randn(3,4)
third_2d_tensor = torch.randn(4,5)
fourth_2d_tensor = torch.randn(5,6)
fifth_2d_tensor = torch.randn(6,7)
torch.linalg.multi_dot((first_2d_tensor,second_2d_tensor,third_2d_tensor,fourth_2d_tensor,fifth_2d_tensor))


tensor([[  1.2183,   7.7378,   9.1392,   4.3350,  -8.6978,   4.2029,  11.6419],
        [  7.3700,  30.9822,  36.3024,  11.9192, -33.1553,  16.7311,  42.0442]])