<a href="https://colab.research.google.com/github/thakur785/sandbox_ai/blob/deeplearnig_pytorc/Pytorch/Deeplearningwithpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu128
True


Creating Tensor CPU example

In [ ]:
import torch
first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])
add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [ ]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating tensor GPU example

In [ ]:
import torch
print(torch.__version__)


2.9.0+cu128


In [ ]:
if torch.cuda.is_available(): device = "cuda"
else : device = "cpu"
print(device)

cuda


In [ ]:
tens_a = torch.tensor([[10,11,12,13],[14,15,16,17]], device = device)
tens_b = torch.tensor([[18,19,20,21],[22,23,24,25]], device = device)
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]], device='cuda:0')


Different ways to create tensors

In [ ]:
import torch
import numpy as np

tensor_from_list = torch.tensor([[1,2,3,4],[5,6,7,8]])
tensor_from_tuple = torch.tensor(((1,2,3,4),(5,6,7,8)))
print("tensor from list")
print(tensor_from_list)
print("tensor from tuple")
print(tensor_from_tuple)

tensor from list
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor from tuple
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
tensor_from_array = torch.tensor(np.array([11,12,13,14,15]))
print(tensor_from_array)

tensor([11, 12, 13, 14, 15])


Different functions for creating tensors


In [ ]:
tensor_emp = torch.empty(3,4)
print("empty tensor", tensor_emp)

empty tensor tensor([[ 1.1948e+13,  4.4970e-41,  1.8077e-43,  0.0000e+00],
        [-8.5339e-32,  4.4972e-41,  1.7544e-08,  0.0000e+00],
        [ 1.1949e+13,  4.4970e-41,  1.6413e-38,  0.0000e+00]])


In [ ]:
tensor_zeros = torch.zeros(3,4)
print("zeros tensor", tensor_zeros)

zeros tensor tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
tensor_ones = torch.ones(3,4)
print("ones tensor", tensor_ones)

ones tensor tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(3,4)
print("random tensor", tensor_rand_un)
tensor_rand_norm = torch.randn(3,4)
print("random normal tensor", tensor_rand_norm)

random tensor tensor([[0.6779, 0.9679, 0.3722, 0.2360],
        [0.8971, 0.5406, 0.8699, 0.7965],
        [0.6343, 0.7491, 0.3978, 0.4595]])
random normal tensor tensor([[-1.6030,  1.1690,  0.2953,  0.8439],
        [-0.9203,  0.7793,  1.1797, -1.0250],
        [ 1.5558, -0.7685,  0.0389, -0.8939]])


Manipulate tensors


In [5]:
import torch

one_dim_tensor = torch.tensor([1,2,3,4,5,6])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

#slicing of tensor
one_dim_tensor[1:4]

tensor(3)
3


tensor([2, 3, 4])

In [6]:
#Indexing two dim tensor
two_dim_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(two_dim_tensor)
two_dim_tensor[1,3]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


tensor(9)

In [7]:
#slicing 2-Dim tensor example
print("first three elements of first row", two_dim_tensor[0,0:3])
print("elements of first row", two_dim_tensor[0,:])


first three elements of first row tensor([1, 2, 3])
elements of first row tensor([1, 2, 3, 4, 5])


In [8]:
#extract 2-Dim tensor that meet some criteria
print(two_dim_tensor[two_dim_tensor<11])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [13]:
#combine 2-Dim tensor
combin_2d_tensors = torch.stack((two_dim_tensor,two_dim_tensor,two_dim_tensor,two_dim_tensor))
print(combin_2d_tensors)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]])


In [15]:
#splitting tensors
first_tensor, second_tensor, third_tensor, fourth_tensor = torch.unbind(two_dim_tensor)
print(first_tensor)
print(second_tensor)
print(third_tensor)
print(fourth_tensor)

tensor([1, 2, 3, 4, 5])
tensor([ 6,  7,  8,  9, 10])
tensor([11, 12, 13, 14, 15])
tensor([16, 17, 18, 19, 20])
