<a href="https://colab.research.google.com/github/thakur785/sandbox_ai/blob/deeplearnig_pytorc/Pytorch/Deeplearningwithpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.9.0+cu128
True


Creating Tensor CPU example

In [2]:
import torch
first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
second_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])
add_tens = first_tens + second_tens
print(add_tens)
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [3]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating tensor GPU example

In [4]:
import torch
print(torch.__version__)


2.9.0+cu128


In [5]:
if torch.cuda.is_available(): device = "cuda"
else : device = "cpu"
print(device)

cuda


In [7]:
tens_a = torch.tensor([[10,11,12,13],[14,15,16,17]], device = device)
tens_b = torch.tensor([[18,19,20,21],[22,23,24,25]], device = device)
multi_tens = tens_a * tens_b
print(multi_tens)

tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]], device='cuda:0')
